# Generated by Django 4.0.6 on 2022-07-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=500)),
                ('length', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('top_speed', models.CharField(max_length=100)),
                ('preferred_prey', models.CharField(max_length=100)),
            ],
        ),
    ]
