# Generated by Django 4.0.6 on 2022-07-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shark',
            name='image',
            field=models.URLField(max_length=500),
        ),
    ]
