# Generated by Django 4.0.6 on 2022-07-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beach_name', models.CharField(max_length=100, null=True)),
                ('city_state', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='shark',
            name='sightings',
            field=models.ManyToManyField(to='sharkapp.sighting'),
        ),
    ]
