# Generated by Django 4.0.6 on 2022-07-29 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0002_alter_shark_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaterBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salinity', models.CharField(choices=[('Fr', 'Fresh Water'), ('Sa', 'Salt Water'), ('Br', 'Brackish (Mix of Salt and Fresh Water)')], default='Sa', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Coasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharkapp.waterbody')),
            ],
        ),
    ]
