# Generated by Django 4.0.6 on 2022-07-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0003_shark_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shark',
            name='sightings',
        ),
        migrations.AddField(
            model_name='sighting',
            name='shark',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sharkapp.shark'),
            preserve_default=False,
        ),
    ]
