# Generated by Django 4.0.6 on 2022-07-29 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0003_waterbody_coasts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Coasts',
            new_name='Coast',
        ),
    ]
