# Generated by Django 4.0.6 on 2022-07-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0004_rename_coasts_coast'),
    ]

    operations = [
        migrations.AddField(
            model_name='coast',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coast',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='coast',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='waterbody',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
