# Generated by Django 4.0.6 on 2022-07-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0004_remove_shark_sightings_sighting_shark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sighting',
            name='shark_species',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
