# Generated by Django 4.0.6 on 2022-07-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0005_coast_city_coast_country_coast_name_waterbody_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shark',
            name='water_bodies',
            field=models.ManyToManyField(to='sharkapp.waterbody'),
        ),
    ]
