# Generated by Django 4.0.6 on 2022-07-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharkapp', '0005_sighting_shark_species'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='shark',
        ),
        migrations.AddField(
            model_name='shark',
            name='sightings',
            field=models.ManyToManyField(to='sharkapp.sighting'),
        ),
    ]
